<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
		<meta charset="utf-8" />
        <title>API v3</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
		<link rel="apple-touch-icon" href="http://<?= parse_url($_SERVER['HTTP_HOST'], PHP_URL_HOST); ?>/themes/enhanced/assets/img/favicon.png?v=1.0">
		<link rel="apple-touch-icon" sizes="76x76" href="http://<?= parse_url($_SERVER['HTTP_HOST'], PHP_URL_HOST); ?>/themes/enhanced/assets/img/favicon.png?v=1.0">
		<link rel="apple-touch-icon" sizes="120x120" href="http://<?= parse_url($_SERVER['HTTP_HOST'], PHP_URL_HOST); ?>/themes/enhanced/assets/img/favicon.png?v=1.0">
		<link rel="apple-touch-icon" sizes="152x152" href="http://<?= parse_url($_SERVER['HTTP_HOST'], PHP_URL_HOST); ?>/themes/enhanced/assets/img/favicon.png?v=1.0">
		<link rel="icon" type="image/x-icon" href="http://<?= parse_url($_SERVER['HTTP_HOST'], PHP_URL_HOST); ?>/themes/enhanced/assets/img/favicon.png?v=1.0" />
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-touch-fullscreen" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="default">
		<meta content="" name="description" />
		<meta content="" name="author" />
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #000;
                font-family: 'Helvetica Neue', sans-serif;
                font-size: 12px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <img src="http://<?= parse_url($_SERVER['HTTP_HOST'], PHP_URL_HOST); ?>/themes/enhanced/assets/img/logo.png?v=1.0" height="100px;">
        <h1>API v3</h1>
    </body>
</html>
